"""Prometheus metrics for the Ollama proxy exporter."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from time import perf_counter
from typing import Any

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Histogram,
    generate_latest,
)

NANOSECONDS_PER_SECOND = 1_000_000_000

PROXY_REQUESTS_TOTAL = Counter(
    "ollama_proxy_requests_total",
    "Total proxied Ollama API requests",
    labelnames=("endpoint", "method", "status_code"),
)
PROXY_REQUEST_DURATION_SECONDS = Histogram(
    "ollama_proxy_request_duration_seconds",
    "End-to-end time spent proxying an Ollama API request",
    labelnames=("endpoint", "method"),
)
PROXY_UPSTREAM_EXCEPTIONS_TOTAL = Counter(
    "ollama_proxy_upstream_exceptions_total",
    "Upstream errors encountered while proxying Ollama requests",
    labelnames=("endpoint", "method", "error_type"),
)
INFERENCE_REQUESTS_TOTAL = Counter(
    "ollama_inference_requests_total",
    "Completed Ollama inference requests observed by the proxy",
    labelnames=("endpoint", "model"),
)
PROMPT_TOKENS_TOTAL = Counter(
    "ollama_prompt_tokens_total",
    "Prompt tokens processed by Ollama",
    labelnames=("endpoint", "model"),
)
GENERATED_TOKENS_TOTAL = Counter(
    "ollama_generated_tokens_total",
    "Completion tokens generated by Ollama",
    labelnames=("endpoint", "model"),
)
PROMPT_EVAL_SECONDS_TOTAL = Counter(
    "ollama_prompt_eval_seconds_total",
    "Time spent evaluating prompt tokens in Ollama",
    labelnames=("endpoint", "model"),
)
EVAL_SECONDS_TOTAL = Counter(
    "ollama_eval_seconds_total",
    "Time spent generating completion tokens in Ollama",
    labelnames=("endpoint", "model"),
)
LOAD_SECONDS_TOTAL = Counter(
    "ollama_load_seconds_total",
    "Time spent loading Ollama models for observed inference requests",
    labelnames=("endpoint", "model"),
)
TOTAL_INFERENCE_SECONDS_TOTAL = Counter(
    "ollama_inference_seconds_total",
    "Total Ollama inference duration reported by the upstream response",
    labelnames=("endpoint", "model"),
)


@dataclass(slots=True)
class InferenceStats:
    """Subset of Ollama response fields used for metrics."""

    endpoint: str
    model: str
    prompt_eval_count: int
    eval_count: int
    prompt_eval_duration_seconds: float
    eval_duration_seconds: float
    load_duration_seconds: float
    total_duration_seconds: float

    @classmethod
    def from_payload(cls, endpoint: str, payload: Mapping[str, Any]) -> InferenceStats | None:
        """Extract stats from a completed Ollama response payload."""

        if not payload.get("done", True):
            return None

        model = str(payload.get("model") or "unknown")
        prompt_eval_count = int(payload.get("prompt_eval_count") or 0)
        eval_count = int(payload.get("eval_count") or 0)
        prompt_eval_duration_seconds = _nanoseconds_to_seconds(payload.get("prompt_eval_duration"))
        eval_duration_seconds = _nanoseconds_to_seconds(payload.get("eval_duration"))
        load_duration_seconds = _nanoseconds_to_seconds(payload.get("load_duration"))
        total_duration_seconds = _nanoseconds_to_seconds(payload.get("total_duration"))

        has_inference_fields = any(
            (
                prompt_eval_count,
                eval_count,
                prompt_eval_duration_seconds,
                eval_duration_seconds,
                load_duration_seconds,
                total_duration_seconds,
            )
        )
        if not has_inference_fields:
            return None

        return cls(
            endpoint=endpoint,
            model=model,
            prompt_eval_count=prompt_eval_count,
            eval_count=eval_count,
            prompt_eval_duration_seconds=prompt_eval_duration_seconds,
            eval_duration_seconds=eval_duration_seconds,
            load_duration_seconds=load_duration_seconds,
            total_duration_seconds=total_duration_seconds,
        )


class RequestTimer:
    """Simple request timer helper."""

    def __init__(self) -> None:
        self._started = perf_counter()

    def elapsed(self) -> float:
        """Return elapsed wall-clock time."""

        return perf_counter() - self._started


def record_proxy_request(
    endpoint: str, method: str, status_code: int, duration_seconds: float
) -> None:
    """Record request volume and latency for a proxied request."""

    PROXY_REQUESTS_TOTAL.labels(
        endpoint=endpoint,
        method=method.upper(),
        status_code=str(status_code),
    ).inc()
    PROXY_REQUEST_DURATION_SECONDS.labels(endpoint=endpoint, method=method.upper()).observe(
        duration_seconds
    )


def record_upstream_exception(
    endpoint: str, method: str, error_type: str, duration_seconds: float
) -> None:
    """Record a failed upstream request."""

    PROXY_UPSTREAM_EXCEPTIONS_TOTAL.labels(
        endpoint=endpoint,
        method=method.upper(),
        error_type=error_type,
    ).inc()
    PROXY_REQUEST_DURATION_SECONDS.labels(endpoint=endpoint, method=method.upper()).observe(
        duration_seconds
    )


def record_inference_stats(stats: InferenceStats) -> None:
    """Increment counters for a completed inference response."""

    INFERENCE_REQUESTS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc()
    PROMPT_TOKENS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc(
        stats.prompt_eval_count
    )
    GENERATED_TOKENS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc(stats.eval_count)
    PROMPT_EVAL_SECONDS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc(
        stats.prompt_eval_duration_seconds
    )
    EVAL_SECONDS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc(
        stats.eval_duration_seconds
    )
    LOAD_SECONDS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc(
        stats.load_duration_seconds
    )
    TOTAL_INFERENCE_SECONDS_TOTAL.labels(endpoint=stats.endpoint, model=stats.model).inc(
        stats.total_duration_seconds
    )


def render_metrics() -> bytes:
    """Render all registered Prometheus metrics."""

    return generate_latest()


def metrics_content_type() -> str:
    """Prometheus exposition content type."""

    return CONTENT_TYPE_LATEST


def _nanoseconds_to_seconds(value: Any) -> float:
    if value in (None, ""):
        return 0.0
    return float(value) / NANOSECONDS_PER_SECOND
